# Generated by Django 4.0.5 on 2022-06-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('first_surname', models.CharField(max_length=25)),
                ('second_surname', models.CharField(max_length=25)),
                ('cell_number', models.BigIntegerField()),
                ('birthday', models.CharField(max_length=10)),
                ('birthplace', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=25)),
                ('income', models.IntegerField()),
                ('curp', models.CharField(max_length=25)),
            ],
        ),
    ]
