# Generated by Django 4.0.5 on 2022-06-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='card_type',
            field=models.CharField(choices=[('BL', 'Black'), ('GD', 'Golden'), ('SV', 'Silver')], default='SV', max_length=2),
        ),
    ]
