# Generated by Django 4.0.5 on 2022-06-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='sex',
        ),
        migrations.AddField(
            model_name='request',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1),
        ),
    ]
